// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpbbjptukyfhhransbuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwYmJqcHR1a3lmaGhyYW5zYnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDYyNTIsImV4cCI6MjA2MjM4MjI1Mn0.o_H5ceTjHarIGDh7nMl-fvwEDX8KtkWWBKDrBwoHr-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);